server:
  port: 9090


spring:
  kafka:
    bootstrap-servers: 192.168.68.111:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/wxoss?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.68.111:3306/economy?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  profiles:
    active: prod
elasticsearch:
  host: 192.168.68.111
    username:
    passwrod:
